name: Checks Pass

on:
  pull_request:
    branches: ["master"]

jobs:
  checks-pass:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - uses: upsidr/merge-gatekeeper@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          self: checks-pass
