name: Test Dagger
on:
  workflow_dispatch: {}
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: michaelmass/actions/dagger@master
        with:
          source: dagger/test/index.ts
          infisical-token: ${{ secrets.INFISICAL_TOKEN }}
          infisical-workspace-id: ${{ secrets.INFISICAL_WORKSPACE_ID }}
